# Connector/Python 中的异常处理

> 原文：<https://overiq.com/mysql-connector-python-101/exception-handling-in-connector-python/>

最后更新于 2020 年 7 月 27 日

* * *

编程时错误总是发生，所以最好装备自己如何处理它们。

## 错误和警告

MySQL 中有两个级别的错误消息严重性。

1.  错误
2.  警告

### 错误

错误表示查询或命令有问题，导致无法执行。

```py
mysql> select * from earth;
ERROR 1146 (42S02): Table 'world.earth' doesn't exist

```

### 警告

警告告诉您发生了一些意想不到的事情，可能会导致问题，但还不足以阻止语句执行。我们可以使用`SHOW WARNINGS;`命令显示警告。例如:

```py
mysql> 
mysql> CREATE database if not exists world;
Query OK, 1 row affected, 1 warning (0.00 sec)

mysql> show warnings;
+-------+------+------------------------------------------------+
| Level | Code | Message                                        |
+-------+------+------------------------------------------------+
| Note  | 1007 | Can't create database 'world'; database exists |
+-------+------+------------------------------------------------+
1 row in set (0.00 sec)

mysql> 
mysql> 
mysql> SELECT 1/0;
+------+
| 1/0  |
+------+
| NULL |
+------+
1 row in set, 1 warning (0.12 sec)

mysql> show warnings;
+---------+------+---------------+
| Level   | Code | Message       |
+---------+------+---------------+
| Warning | 1365 | Division by 0 |
+---------+------+---------------+
1 row in set (0.00 sec)
mysql>

```

### 错误代码

MySQL 中的错误和警告包含三条信息:

```py
mysql> select * from earth;
ERROR 1146 (42S02): Table 'world.earth' doesn't exist

```

1.  不可移植到其他数据库的唯一 MySQL 特定错误代码(`1146`)。

2.  一个 5 字符代码(`42S02`)称为 [SQLSTATE](https://en.wikipedia.org/wiki/SQLSTATE) ，用于指示操作的成功或失败。SQLSTATE 可以跨其他数据库移植。它由两部分组成:前两个字符代表 SQL 错误类，后三个字符代表子类。每个类可以属于以下四个类别之一。

    1.  成功(00 级)
    2.  警告(01 级)
    3.  无数据(02 级)
    4.  例外(所有其他 07-HZ)
3.  错误的文本描述。

那么为什么是两个错误代码呢？

这是因为`SQLSTATE`代表一组[错误](https://dev.mysql.com/doc/refman/8.0/en/server-error-reference.html)。因此，我们只能用它来处理一般性错误。如果您想处理一些特定的错误，请使用 MySQL 特定的错误代码。

有数百个 MySQL 特有的错误代码。幸运的是，您不需要记住它们，因为`mysql.connector.errorcode`模块包含了所有 MySQL 特有的错误代码。

```py
>>> 
>>> from mysql.connector import errorcode
>>> errorcode.ER_BAD_TABLE_ERROR
1051
>>>

```

## 例外类

所有用于处理错误和警告的异常类都在`mysql.connector.errors`模块中定义。

`mysql.connector.errors.Error`是所有其他异常的基类。我们可以用它来捕捉任何类型的异常。

这里有一个例子:

```py
import mysql.connector

db = mysql.connector.connect(option_files='my.conf', use_pure=True)

cursor = db.cursor()

sql = """
CREATE TABLE `city` (
  `ID` int(11) AUTO_INCREMENT PRIMARY KEY,
  `Name` char(35) NOT NULL DEFAULT '',
  `CountryCode` char(3) NOT NULL DEFAULT ''  
)
"""

try:
    cursor.execute(sql)
    db.commit()

except mysql.connector.Error as err:
    print(err)
    print("Error Code:", err.errno)
    print("SQLSTATE", err.sqlstate)
    print("Message", err.msg)

cursor.close()
db.close()

```

**预期输出:**

```py
1050 (42S01): Table 'city' already exists
Error Code: 1050
SQLSTATE 42S01
Message Table 'city' already exists

```

当抛出异常时，您可以访问异常对象的错误代码、SQLSTATE 和以`errno`、`sqlstate`和`msg`属性形式出现的错误消息。

`mysql.connector.errors.Error`基类进一步细分为以下三个类:

1.  `DatabaseError`
2.  `InterfaceError`
3.  `PoolError`

我们一个一个来讨论。

1.  `DatabaseError`:与数据库相关的错误引发此异常。它可以捕捉各种错误，如数据处理问题、SQL 语法错误、MySQL 内部问题等。如果建立了连接并且出现了问题，那么`DatabaseError`将会抓住它。`DatabaseError`有 6 种类型:

    1.  `DataError`
    2.  `InternalError`
    3.  `IntegrityError`
    4.  `OperationalError`
    5.  `NotSupportedError`
    6.  `ProgrammingError`

    * * *

    1.  `DataError`:该错误表示数据处理有问题，如被零除、数值超出范围、类型无效等。
    2.  `InternalError`:当数据库遇到内部错误时，会引发此异常。例如无效光标、事务不同步等。
    3.  `IntegrityError`:当外键约束失败时，会引发此异常。
    4.  `OperationalError`:对于程序员无法控制的事情，会引发这个异常。例如，意外断开、内存分配错误等、事务失败，选定的数据库不存在。
    5.  `NotSupportedError`:调用不支持的方法或 api 时，会引发此异常。例如，在不支持事务的连接上调用`rollback()`。
    6.  `ProgrammingError`:编程错误引发此异常。例如，表未找到或已经存在，MySQL 语法错误，指定的参数数量错误，连接凭证错误等。
2.  `InterfaceError`:这个异常是针对与接口相关的错误(在我们的例子中接口是 MySQL Connector/Python)而不是数据库本身引发的。

3.  `PoolError`:针对连接池相关的错误引发。我们将在下一章中学习连接池。

下图显示了异常类的层次结构:

```py
StandardError
|__ Error
    |__ InterfaceError
    |__ PoolError
    |__ DatabaseError
        |__ DataError
        |__ InternalError 
        |__ IntegrityError
        |__ OperationalError        
        |__ NotSupportedError
        |__ ProgrammingError

```

所有异常类都映射到一个或多个 SQLSTATE 类，您可以通过键入以下命令来打印此映射。

```py
>>>
>>> from mysql.connector import errors
>>> from pprint import pprint
>>> 
>>> pprint(errors._SQLSTATE_CLASS_EXCEPTION)
{'02': <class 'mysql.connector.errors.DataError'>,
 '07': <class 'mysql.connector.errors.DatabaseError'>,
 '08': <class 'mysql.connector.errors.OperationalError'>,
 '0A': <class 'mysql.connector.errors.NotSupportedError'>,
 '0K': <class 'mysql.connector.errors.OperationalError'>,
...
 'HY': <class 'mysql.connector.errors.DatabaseError'>,
 'HZ': <class 'mysql.connector.errors.OperationalError'>,
 'XA': <class 'mysql.connector.errors.IntegrityError'>}
>>> 
>>>

```

现在我们来看一些例子。

示例 1:处理一般错误

```py
import mysql.connector

db = mysql.connector.connect(option_files='my.conf', use_pure=True)

cursor = db.cursor()

sql = """
select * from town limit 5
"""

try:
    cursor.execute(sql)

    for row in cursor:
        print(row)

    cursor.close()
    db.close()

except mysql.connector.ProgrammingError as err:
    print(err.errno)
    print(err.sqlstate)
    print(err.msg)

except mysql.connector.Error as err:
    print(err)

```

请记住`ProgrammingError`可以捕捉从语法错误到找不到表的各种异常。如果您想捕捉一些特定的错误，请使用`errorcode`模块。

示例 2:处理特定错误

```py
import mysql.connector
from mysql.connector import errorcode

db = mysql.connector.connect(option_files='my.conf', use_pure=True)

cursor = db.cursor()

sql = """
select * from town limit 5
"""

try:
    cursor.execute(sql)

    for row in cursor:
        print(row)

    db.close()

except mysql.connector.ProgrammingError as err:
    if errorcode.ER_NO_SUCH_TABLE == err.errno:
        print("No table exists")
    else:
        print("Table exists")
        print(err)

except mysql.connector.Error as err:
    print("Some other error")
    print(err)

```

示例 3:以相同的方式处理多个错误

```py
import mysql.connector

db = mysql.connector.connect(option_files='my.conf', use_pure=True)

cursor = db.cursor()

sql = """
insert into city(Name, CountryCode, District, Population)
VALUES ('Kabul', 'AFGANISTAN', 'Kabol', 1780000)
"""

try:
    cursor.execute(sql)

    db.commit()
    db.close()

except (mysql.connector.IntegrityError, mysql.connector.DataError) as err:
    print("DataError or IntegrityError")
    print(err)

except mysql.connector.ProgrammingError as err:
    print("Programming Error")
    print(err)

except mysql.connector.Error as err:
    print(err)

```

## 处理警告

默认情况下，MySQL Connector/Python 既不获取警告，也不在出现警告时引发异常。但是，我们可以使用`connect()`函数的以下参数来改变这一点。

| 争吵 | 描述 |
| --- | --- |
| `get_warnings` | 如果设置为`True`，则每次查询后自动获取警告，无需手动执行`SHOW WARNINGS`查询。其默认值为`False`。 |
| `raise_on_warnings` | 如果设置为`True`，出现警告时会引发异常。默认为`False`。设置`raise_on_warnings=True`，也设置`get_warnings=True` |

以上两个参数也可用作连接对象的属性，可用于设置和检索当前设置。

```py
import mysql.connector
from mysql.connector import errors

db = mysql.connector.connect(option_files='my.conf')

db.get_warnings = True  # this is not required if raise_on_warnings=True
db.raise_on_warnings = True

```

设置`get_warnings=True`(或`raise_on_warnings=True`)后，使用光标对象的`fetchwarnings()`方法检索实际警告。`fetchwarnings()`方法返回一个元组列表，其中包含消息级、错误代码和由之前执行的查询生成的消息本身。

下面的示例演示如何获取查询产生的警告:

```py
import mysql.connector

db = mysql.connector.connect(option_files='my.conf',
                             get_warnings=True)

# db.get_warnings = True  # we could have set get_warnings like this too

cursor = db.cursor()

cursor.execute("CREATE database if not exists world;")
print(cursor.fetchwarnings())

cursor.execute("select 1/0;")
cursor.fetchall() # fetch all the rows from the result set
print(cursor.fetchwarnings())

```

**预期输出:**

```py
[('Note', 1007, "Can't create database 'world'; database exists")]
[('Warning', 1365, 'Division by 0')]

```

请注意，如果查询返回结果集(如`SELECT`语句)，那么您需要在调用`fetchwarnings()`方法之前获取所有行，否则`fetchwarnings()`方法将返回`None`。

下面是一个示例，展示了如何在出现警告时引发异常。

```py
import mysql.connector
from mysql.connector import errors

db = mysql.connector.connect(option_files='my.conf',
                             raise_on_warnings=True)

# db.raise_on_warnings = True  # we could have set raise_on_warnings like this

cursor = db.cursor()

try:

    cursor.execute("CREATE database if not exists world;")
    print(cursor.fetchwarnings())

    cursor.execute("select 1/0;")
    print(cursor.fetchall()) # fetch all the rows from the result set
    print(cursor.fetchwarnings())

except errors.DatabaseError as e:
    print(e)

except:
    print('some error occurred')

```

**预期输出:**

```py
1007: Can't create database 'world'; database exists

```

注意设置`raise_on_warnings=True`会隐式设置`get_warnings=True`。

您现在应该对如何处理错误有了一个很好的了解。在接下来的几页中，我们将看到一些实用的`SELECT`、`INSERT`、`UPDATE`和`DELTETE`语句示例:

* * *

* * *